### ISSUE TITLE
api explorer - encode user input to be valid and notify them of the change

### ISSUE THREAD

**Issue by geekcyclist** [agrc/api.mapserv.utah.gov#120]
Use an address like
Street: 135 S 300 E #108 
or 
Street: 135 S 300 E # 108 
with
Zone: 84111
All other settings as default

Click "Try It"

Expected behavior
The search would behave the same as if searching "135 S 300 E  Unit 108" or "135 S 300 E  Apt 108 "

Actual behavior 
The Try It button changes to the "zebra" background
The cursor hover over the Try It button changes to the "universal no"
You can click and change data, and can submit again, even thought the button and cursor appearance has changed, but it is confusing to users.

**Comment by steveoh** [comment]
The current explorer page is not smart enough to turn that pound sign hashtag octothorpe (url reserved character) into a %23 for valid use in a url. We should improve this in the new explorer page we are working on but I kind of enjoy that it doesn't work since it wouldn't work as a normal get request in that state. Expecting people to know that will be problematic so we should "fix" the url and display a warning to the user that we had to modify the characters.

I'm going to update the issue to become the new feature but for the time being, encode your urls!

cc @stdavis - this could be a feature to work on for the new explorer
