### ISSUE TITLE
100 score for a wrong location when omitting street direction

### ISSUE THREAD

**Issue by jacobdadams** [agrc/api.mapserv.utah.gov#161]
When I enter `355 Main St, 84741` (which is in Kanab), I get a 100 score match in Cannonville. If I search using Masquerade as my Pro locator, the first 5 or 6 results are not even in Kane County.

If I add the proper street direction `355 N Main St, 84741` it locates perfectly and accurately. 

I'm perplexed why it would return a 100 score match when the returned location isn't in the zip code provided.

**Comment by steveoh** [comment]
## Address System mapping

84741 is mapped to these address grids:

zip | grid | weight
-- | -- | --
84741 | BIG WATER | 2
84741 | BULLFROG | 0
84741 | CANNONVILLE | 1
84741 | KANAB | 3

<img width="869" alt="image" src="https://user-images.githubusercontent.com/325813/191046820-93794ca0-c596-41de-bce8-ab7f69175da2.png">

## api.utah.gov 

The top matches chosen from the api are

1. 355 MAIN ST, Cannonville: 100
2. 355 N MAIN ST, KANAB: 92.43
3. 355 S MAIN ST, Cannonville: 92.43
4. 355 MAIN ST, KAMAS : 87.42
5. 355 MAIN ST, BEAVER : 83.53

## Roads locators

### kanab

1. 355 N MAIN ST, Kanab : 89.74
2. 355 S MAIN ST, Kanab : 89.74

### big water

_no matches_

### cannonville

1. 355 MAIN ST, Cannonville : 97.31
2. 355 S MAIN ST, Cannonville : 89.74

### bull frog

_no matches_

## Address point locators

### kanab

1. 355 N MAIN ST, Kanab : 92.43
2. 355 S MAIN ST, Kanab : 92.43

### big water

1.  355 MAIN ST, BEAVER : 83.53

### cannonville

1. 355 MAIN ST, CIRCLEVILLE : 81.12

### bull frog

1. 355 MAIN ST, FILLMORE : 82.84


## thoughts

Since there are 4 address systems I would assume that 355 main street could exists in each of them. Since main streets typically have a north and south the scores are tied between those two points. Cannonville must not have a north main street so it matches higher. Presumably there is an alt table entry omitting the south because it's not required. Greg could confirm that.

I don't know why the address point locator is returning results outside of it's address system. That is super strange and possibly the only bug I can see from this issue. Beaver should never be included in the response. I'm not sure what other actionable items there would be when searching for this incomplete address. Hopefully you have some ideas?

**Comment by steveoh** [comment]
closing as stale
